#DB Configuration:
spring:

  #Redis
  redis:
    host: 106.15.176.125
    port: 6379

  mail:
    host: smtp.qq.com
    username: 1447076355@qq.com # 这里填写个人的qq邮箱
    password: aghmefjkwysdihfg # 注：这里不是qq邮箱的密码，而是授权码
    default-encoding: UTF-8
#发送地址
mail:
 fromMail:
      addr: 1447076355@qq.com

logging:
  level:
    com:
      hnit: debug
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

    
# mybatis缓存
mybatis:
  configuration:
    cache-enabled: true



